//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.12 at 07:33:54 PM IST 
//


package com.wecodee.webservice.schoolfeeservice;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FeePaymentDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeePaymentDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PAYMENT_REF_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PAYMENT_CYCLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FIRST_DUE_DT" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="NO_OF_PAYMENTS" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="TOTAL_FEE_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="DISCOUNTED_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="TOTAL_EFF_FEE_AMT" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="PaymentScheduleDetails" type="{http://webservice.wecodee.com/schoolfeeservice}PaymentScheduleDetails" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeePaymentDetails", propOrder = {
    "paymentrefno",
    "paymentcycle",
    "firstduedt",
    "noofpayments",
    "totalfeeamount",
    "discountedamount",
    "totalefffeeamt",
    "paymentScheduleDetails"
})
public class FeePaymentDetails {

    @XmlElement(name = "PAYMENT_REF_NO", required = true)
    protected String paymentrefno;
    @XmlElement(name = "PAYMENT_CYCLE", required = true)
    protected String paymentcycle;
    @XmlElement(name = "FIRST_DUE_DT", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstduedt;
    @XmlElement(name = "NO_OF_PAYMENTS", required = true)
    protected BigInteger noofpayments;
    @XmlElement(name = "TOTAL_FEE_AMOUNT")
    protected double totalfeeamount;
    @XmlElement(name = "DISCOUNTED_AMOUNT")
    protected double discountedamount;
    @XmlElement(name = "TOTAL_EFF_FEE_AMT")
    protected double totalefffeeamt;
    @XmlElement(name = "PaymentScheduleDetails")
    protected List<PaymentScheduleDetails> paymentScheduleDetails;

    /**
     * Gets the value of the paymentrefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTREFNO() {
        return paymentrefno;
    }

    /**
     * Sets the value of the paymentrefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTREFNO(String value) {
        this.paymentrefno = value;
    }

    /**
     * Gets the value of the paymentcycle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAYMENTCYCLE() {
        return paymentcycle;
    }

    /**
     * Sets the value of the paymentcycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAYMENTCYCLE(String value) {
        this.paymentcycle = value;
    }

    /**
     * Gets the value of the firstduedt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFIRSTDUEDT() {
        return firstduedt;
    }

    /**
     * Sets the value of the firstduedt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFIRSTDUEDT(XMLGregorianCalendar value) {
        this.firstduedt = value;
    }

    /**
     * Gets the value of the noofpayments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNOOFPAYMENTS() {
        return noofpayments;
    }

    /**
     * Sets the value of the noofpayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNOOFPAYMENTS(BigInteger value) {
        this.noofpayments = value;
    }

    /**
     * Gets the value of the totalfeeamount property.
     * 
     */
    public double getTOTALFEEAMOUNT() {
        return totalfeeamount;
    }

    /**
     * Sets the value of the totalfeeamount property.
     * 
     */
    public void setTOTALFEEAMOUNT(double value) {
        this.totalfeeamount = value;
    }

    /**
     * Gets the value of the discountedamount property.
     * 
     */
    public double getDISCOUNTEDAMOUNT() {
        return discountedamount;
    }

    /**
     * Sets the value of the discountedamount property.
     * 
     */
    public void setDISCOUNTEDAMOUNT(double value) {
        this.discountedamount = value;
    }

    /**
     * Gets the value of the totalefffeeamt property.
     * 
     */
    public double getTOTALEFFFEEAMT() {
        return totalefffeeamt;
    }

    /**
     * Sets the value of the totalefffeeamt property.
     * 
     */
    public void setTOTALEFFFEEAMT(double value) {
        this.totalefffeeamt = value;
    }

    /**
     * Gets the value of the paymentScheduleDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentScheduleDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentScheduleDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentScheduleDetails }
     * 
     * 
     */
    public List<PaymentScheduleDetails> getPaymentScheduleDetails() {
        if (paymentScheduleDetails == null) {
            paymentScheduleDetails = new ArrayList<PaymentScheduleDetails>();
        }
        return this.paymentScheduleDetails;
    }

}
