//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.12 at 07:33:54 PM IST 
//


package com.wecodee.webservice.schoolfeeservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for header complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="header"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SOURCE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UBSCOMP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="USERID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BRANCH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SERVICE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OPERATION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MSGSTAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "header", propOrder = {
    "source",
    "ubscomp",
    "userid",
    "branch",
    "service",
    "operation",
    "msgstat"
})
public class Header {

    @XmlElement(name = "SOURCE", required = true)
    protected String source;
    @XmlElement(name = "UBSCOMP", required = true)
    protected String ubscomp;
    @XmlElement(name = "USERID", required = true)
    protected String userid;
    @XmlElement(name = "BRANCH", required = true)
    protected String branch;
    @XmlElement(name = "SERVICE", required = true)
    protected String service;
    @XmlElement(name = "OPERATION", required = true)
    protected String operation;
    @XmlElement(name = "MSGSTAT")
    protected String msgstat;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCE() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCE(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the ubscomp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUBSCOMP() {
        return ubscomp;
    }

    /**
     * Sets the value of the ubscomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUBSCOMP(String value) {
        this.ubscomp = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERID(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRANCH() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRANCH(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICE() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICE(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPERATION() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPERATION(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the msgstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMSGSTAT() {
        return msgstat;
    }

    /**
     * Sets the value of the msgstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMSGSTAT(String value) {
        this.msgstat = value;
    }

}
