//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.23 at 06:03:04 PM IST 
//


package com.wecodee.webservice.schoolfeeservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueryByStudentDetailsBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueryByStudentDetailsBody"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="STUDENT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ST_GRADE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CAMPUS_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="INSTITUTION_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueryByStudentDetailsBody", propOrder = {
    "studentnumber",
    "stgrade",
    "campusid",
    "institutionid"
})
public class QueryByStudentDetailsBody {

    @XmlElement(name = "STUDENT_NUMBER", required = true)
    protected String studentnumber;
    @XmlElement(name = "ST_GRADE", required = true)
    protected String stgrade;
    @XmlElement(name = "CAMPUS_ID", required = true)
    protected String campusid;
    @XmlElement(name = "INSTITUTION_ID", required = true)
    protected String institutionid;

    /**
     * Gets the value of the studentnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUDENTNUMBER() {
        return studentnumber;
    }

    /**
     * Sets the value of the studentnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUDENTNUMBER(String value) {
        this.studentnumber = value;
    }

    /**
     * Gets the value of the stgrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGRADE() {
        return stgrade;
    }

    /**
     * Sets the value of the stgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGRADE(String value) {
        this.stgrade = value;
    }

    /**
     * Gets the value of the campusid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAMPUSID() {
        return campusid;
    }

    /**
     * Sets the value of the campusid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAMPUSID(String value) {
        this.campusid = value;
    }

    /**
     * Gets the value of the institutionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSTITUTIONID() {
        return institutionid;
    }

    /**
     * Sets the value of the institutionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSTITUTIONID(String value) {
        this.institutionid = value;
    }

}
