//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.12 at 07:33:54 PM IST 
//


package com.wecodee.webservice.schoolfeeservice;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StudentDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StudentDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="STUDENT_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STUDENT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STUDENT_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ST_GRADE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ST_SECTION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ST_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PHONE_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CAMPUS_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CAMPUS_AC_BRANCH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CAMPUS_AC_NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="INSTITUTION_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PARTIAL_PAYMENT" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FeePaymentDetails" type="{http://webservice.wecodee.com/schoolfeeservice}FeePaymentDetails" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StudentDetails", propOrder = {
    "studentid",
    "studentnumber",
    "studentname",
    "stgrade",
    "stsection",
    "stcategory",
    "phoneno",
    "campusid",
    "campusacbranch",
    "campusacno",
    "institutionid",
    "partialpayment",
    "feePaymentDetails"
})
public class StudentDetails {

    @XmlElement(name = "STUDENT_ID", required = true)
    protected String studentid;
    @XmlElement(name = "STUDENT_NUMBER", required = true)
    protected String studentnumber;
    @XmlElement(name = "STUDENT_NAME", required = true)
    protected String studentname;
    @XmlElement(name = "ST_GRADE", required = true)
    protected String stgrade;
    @XmlElement(name = "ST_SECTION", required = true)
    protected String stsection;
    @XmlElement(name = "ST_CATEGORY", required = true)
    protected String stcategory;
    @XmlElement(name = "PHONE_NO", required = true)
    protected String phoneno;
    @XmlElement(name = "CAMPUS_ID", required = true)
    protected String campusid;
    @XmlElement(name = "CAMPUS_AC_BRANCH", required = true)
    protected String campusacbranch;
    @XmlElement(name = "CAMPUS_AC_NO", required = true)
    protected String campusacno;
    @XmlElement(name = "INSTITUTION_ID", required = true)
    protected String institutionid;
    @XmlElement(name = "PARTIAL_PAYMENT", required = true)
    protected String partialpayment;
    @XmlElement(name = "FeePaymentDetails")
    protected List<FeePaymentDetails> feePaymentDetails;

    /**
     * Gets the value of the studentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUDENTID() {
        return studentid;
    }

    /**
     * Sets the value of the studentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUDENTID(String value) {
        this.studentid = value;
    }

    /**
     * Gets the value of the studentnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUDENTNUMBER() {
        return studentnumber;
    }

    /**
     * Sets the value of the studentnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUDENTNUMBER(String value) {
        this.studentnumber = value;
    }

    /**
     * Gets the value of the studentname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUDENTNAME() {
        return studentname;
    }

    /**
     * Sets the value of the studentname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUDENTNAME(String value) {
        this.studentname = value;
    }

    /**
     * Gets the value of the stgrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGRADE() {
        return stgrade;
    }

    /**
     * Sets the value of the stgrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGRADE(String value) {
        this.stgrade = value;
    }

    /**
     * Gets the value of the stsection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTSECTION() {
        return stsection;
    }

    /**
     * Sets the value of the stsection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTSECTION(String value) {
        this.stsection = value;
    }

    /**
     * Gets the value of the stcategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTCATEGORY() {
        return stcategory;
    }

    /**
     * Sets the value of the stcategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTCATEGORY(String value) {
        this.stcategory = value;
    }

    /**
     * Gets the value of the phoneno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONENO() {
        return phoneno;
    }

    /**
     * Sets the value of the phoneno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONENO(String value) {
        this.phoneno = value;
    }

    /**
     * Gets the value of the campusid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAMPUSID() {
        return campusid;
    }

    /**
     * Sets the value of the campusid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAMPUSID(String value) {
        this.campusid = value;
    }

    /**
     * Gets the value of the campusacbranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAMPUSACBRANCH() {
        return campusacbranch;
    }

    /**
     * Sets the value of the campusacbranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAMPUSACBRANCH(String value) {
        this.campusacbranch = value;
    }

    /**
     * Gets the value of the campusacno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAMPUSACNO() {
        return campusacno;
    }

    /**
     * Sets the value of the campusacno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAMPUSACNO(String value) {
        this.campusacno = value;
    }

    /**
     * Gets the value of the institutionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSTITUTIONID() {
        return institutionid;
    }

    /**
     * Sets the value of the institutionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSTITUTIONID(String value) {
        this.institutionid = value;
    }

    /**
     * Gets the value of the partialpayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTIALPAYMENT() {
        return partialpayment;
    }

    /**
     * Sets the value of the partialpayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTIALPAYMENT(String value) {
        this.partialpayment = value;
    }

    /**
     * Gets the value of the feePaymentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the feePaymentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeePaymentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeePaymentDetails }
     * 
     * 
     */
    public List<FeePaymentDetails> getFeePaymentDetails() {
        if (feePaymentDetails == null) {
            feePaymentDetails = new ArrayList<FeePaymentDetails>();
        }
        return this.feePaymentDetails;
    }

}
